name: sleeping_pills
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  animated_introduction: ^1.0.3
  flutter_mobx: ^2.0.1
  mobx: ^2.0.1
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.3.7
  twilio_flutter: ^0.9.0
  random_string: ^2.3.1
  fluttertoast: ^8.2.10
  intl_phone_number_input: ^0.7.4
  http: ^1.2.2
  flutter_screenutil: ^5.9.3
  pin_code_fields: ^8.0.1
  otp_text_field: ^1.1.3
  intl_phone_field: ^3.2.0
  syncfusion_flutter_gauges: ^28.1.41
  syncfusion_flutter_charts: ^28.1.37

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/intro-slide-sleeping-cat.png
    - assets/intro-slide-sleeping-rabit.png
    - assets/intro-slide-sleeping-dog.png

