name: Test, Build and Release APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Sử dụng Ubuntu runner cho Android và macOS runner cho iOS
    runs-on: ubuntu-latest  # Có thể đổi thành macOS nếu cần cho iOS

    steps:
    # 1. Checkout code từ repo
    - uses: actions/checkout@v3
    
    # 2. Thiết lập Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'  # Cập nhật phiên bản Flutter mới nhất

    # 3. Cài đặt dependencies
    - name: Install dependencies
      run: flutter pub get

    # 4. Kiểm tra mã nguồn (test)
    - name: Run tests
      run: flutter test

    # 5. Build APK cho Android (Release)
    - name: Build APK
      run: flutter build apk --release
